# Generated by Django 5.2.3 on 2025-06-14 08:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('place', models.PositiveIntegerField(default=1)),
                ('price', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='rooms_image')),
            ],
            options={
                'verbose_name': ['Кімната'],
                'verbose_name_plural': ['Кімнати'],
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='TypeRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('phone', models.CharField(max_length=20)),
                ('persons', models.PositiveIntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_system.room')),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
                'ordering': ['date_creation', 'date_start', 'date_end'],
            },
        ),
        migrations.AddField(
            model_name='room',
            name='type_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_system.typeroom'),
        ),
    ]
